### ISSUE TITLE
🌙 URGENT: Dark mode for eye comfort

### ISSUE THREAD

**Issue by CalebBarnes** [CalebBarnes/netlify-db-chat-app#22]
## 🌙 URGENT Dark Mode Request

**Requested by**: @bowo (live chat - eyes hurting!)

### User Feedback
- **@bowo**: "can we have dark mode? the white screen is hurting my eyes right now"

### Description
Implement a dark mode theme to reduce eye strain, especially for users who are sensitive to bright white screens.

### Health Impact
- **Eye strain** from bright white background
- **User comfort** during extended chat sessions
- **Accessibility** for light-sensitive users
- **Modern UX standard** - most apps have dark mode

#### 1. Dark Theme Design
- [ ] Dark background (#1a1a1a or #2d3748)
- [ ] Light text (#e2e8f0 or #f7fafc)
- [ ] Dark message bubbles with proper contrast
- [ ] Dark header and sidebar
- [ ] Proper contrast ratios (WCAG AA compliant)

#### 2. Theme Toggle
- [ ] Dark/light mode toggle button in header
- [ ] System preference detection (prefers-color-scheme)
- [ ] Theme persistence in localStorage
- [ ] Smooth transition animations

#### 3. Color Scheme
```css
/* Dark mode variables */
[data-theme="dark"] {
  --background-color: #1a202c;
  --text-color: #e2e8f0;
  --message-bg-own: #4a5568; /* Darker blue for sent messages */
  --message-bg-other: #2d3748; /* Dark gray for received */
  --header-bg: #2d3748;
  --sidebar-bg: #2d3748;
  --input-bg: #4a5568;
  --border-color: #4a5568;
}
```

#### 4. Message Bubble Adjustments
- **Sent messages**: Darker blue (#4a5568) with white text
- **Received messages**: Dark gray (#2d3748) with light text
- **Proper contrast**: Ensure readability in dark mode
- **Bubble tails**: Maintain iMessage-style design

#### Theme System
- Use CSS custom properties for easy theme switching
- JavaScript toggle function
- Detect system preference on first visit
- Save user preference in localStorage

#### Toggle Button
- Add 🌙/☀️ toggle in header next to user panel
- Smooth transition with CSS transitions
- Immediate theme application

#### Accessibility
- Maintain WCAG AA contrast ratios
- Test with screen readers
- Ensure all UI elements are visible in dark mode
- Proper focus indicators

### Priority
**🌙 URGENT** - User experiencing eye discomfort!

### Acceptance Criteria
- [ ] Dark mode toggle working
- [ ] All text readable in dark mode
- [ ] Message bubbles properly styled
- [ ] Theme persists across sessions
- [ ] System preference detection
- [ ] @bowo's eyes feel better! 👀

### Labels
`urgent`, `accessibility`, `dark-mode`, `user-requested`, `eye-comfort`

---

**This is important for user comfort and accessibility!** 🌙👀
