### ISSUE TITLE
🖥️ Desktop viewport optimization - Remove purple background and full viewport

### ISSUE THREAD

**Issue by CalebBarnes** [CalebBarnes/netlify-db-chat-app#26]
## 🖥️ Desktop Viewport Optimization Request

**Requested by**: @brendo (live chat)

### User Feedback
- **@brendo**: "ai assistant, on desktop get rid of the purple background and make the chat experience the entire height and width of the viewport!!!"

### Description
Optimize the desktop experience by removing the purple background and making the chat application use the full viewport dimensions for better space utilization.

### Current Desktop Issues
- **Purple background** taking up unnecessary space
- **Chat container** not using full viewport width/height
- **Wasted screen real estate** on larger desktop screens
- **Inconsistent with mobile** which already uses full viewport

#### 1. Remove Purple Background
- [ ] Eliminate purple background color
- [ ] Use clean white or theme-appropriate background
- [ ] Ensure proper contrast for accessibility
- [ ] Match mobile full-viewport approach

#### 2. Full Viewport Layout
- [ ] Chat container uses 100vw (full viewport width)
- [ ] Chat container uses 100vh (full viewport height)
- [ ] Remove any outer margins/padding on desktop
- [ ] Ensure responsive behavior is maintained

#### 3. Desktop-Specific Optimizations
```css
/* Desktop viewport optimization */
@media (min-width: 769px) {
  .app-container {
    width: 100vw;
    height: 100vh;
    margin: 0;
    padding: 0;
    background: var(--background-color, #ffffff);
  }
  
  .chat-container {
    width: 100%;
    height: 100%;
    max-width: none; /* Remove any max-width constraints */
  }
  
  /* Remove purple background */
  body {
    background: var(--background-color, #ffffff);
    margin: 0;
    padding: 0;
  }
}
```

#### 4. Layout Structure
- **Header**: Fixed at top, full width
- **Chat area**: Flexible height, full width
- **Input area**: Fixed at bottom, full width
- **Sidebar**: Overlay or slide-in on desktop

#### CSS Changes
- Remove purple background from body/html
- Set chat container to use full viewport dimensions
- Ensure proper flexbox layout for desktop
- Maintain mobile responsiveness

#### Responsive Considerations
- Desktop (>768px): Full viewport layout
- Tablet (768px-1024px): Adaptive layout
- Mobile (<768px): Current mobile-optimized layout
- Ultra-wide (>1920px): Consider max-width for readability

#### Desktop Advantages
- **Maximum screen utilization** on large monitors
- **Immersive chat experience** without distracting backgrounds
- **Consistent with modern apps** that use full viewport
- **Better focus** on chat content

#### Visual Improvements
- **Clean, professional appearance** without purple background
- **Edge-to-edge design** like mobile apps
- **Better content density** on desktop screens
- **Reduced visual clutter** from unnecessary backgrounds

### Accessibility Considerations
- Maintain proper contrast ratios
- Ensure focus indicators are visible
- Test with screen readers
- Verify keyboard navigation works properly

### Browser Compatibility
- Test viewport units (vw, vh) across browsers
- Ensure proper fallbacks for older browsers
- Verify mobile Safari viewport behavior
- Test on various desktop resolutions

### Design Consistency
- Match mobile full-viewport approach
- Ensure dark mode compatibility
- Maintain brand colors in UI elements
- Keep consistent spacing and typography

### Priority
**🖥️ MEDIUM-HIGH** - Important for desktop user experience

### Acceptance Criteria
- [ ] Purple background completely removed
- [ ] Chat uses full viewport width and height on desktop
- [ ] No wasted space around chat container
- [ ] Responsive behavior maintained for all screen sizes
- [ ] Accessibility standards met
- [ ] @brendo approves the full viewport experience!

### Labels
`desktop`, `viewport`, `background`, `user-requested`, `ux-improvement`

---

**This will create a much more immersive and professional desktop chat experience!** 🖥️✨
