### ISSUE TITLE
🌸 Kawaii Pastel Theme - Cute Clouds & Soft Colors

### ISSUE THREAD

**Issue by CalebBarnes** [CalebBarnes/netlify-db-chat-app#30]
## 🌸 Kawaii Pastel Theme Request

**Requested by**: @bowo (live chat)

### User Feedback
- **@bowo**: "a super cute kawaii pastel theme should exist! like light pink and light yellow and like lil cute clouds on the banner or wallpaper behind the app uwu"

### Description
Create an adorable kawaii pastel theme featuring soft pink and yellow colors with cute cloud decorations. This theme should embody the kawaii aesthetic that @bowo loves, creating a sweet, gentle, and utterly adorable chat experience.

#### Kawaii Aesthetic Elements
- **Soft pastel colors** - Light pink, light yellow, cream, lavender
- **Cute cloud decorations** - Fluffy clouds in the background
- **Rounded corners** - Everything soft and bubbly
- **Gentle gradients** - Smooth color transitions
- **Kawaii typography** - Soft, friendly fonts
- **Subtle animations** - Gentle floating and pulsing effects

#### Color Palette
```css
/* Kawaii Pastel Theme Colors */
:root[data-theme="kawaii"] {
  /* Primary Colors */
  --bg-primary: linear-gradient(135deg, #fff0f5 0%, #fff8dc 100%); /* Pink to cream */
  --bg-secondary: rgba(255, 240, 245, 0.8);
  --bg-tertiary: rgba(255, 248, 220, 0.6);
  
  /* Text Colors */
  --text-primary: #8b4a6b; /* Soft pink-purple */
  --text-secondary: #a67c8a; /* Muted pink */
  --text-muted: #c9a9b8; /* Light pink */
  
  /* Accent Colors */
  --accent-pink: #ffb3d9; /* Kawaii pink */
  --accent-yellow: #fff2b3; /* Kawaii yellow */
  --accent-lavender: #e6ccff; /* Soft purple */
  --accent-mint: #ccffcc; /* Gentle green */
  
  /* Message Bubbles */
  --message-bg-own: linear-gradient(135deg, #ffb3d9 0%, #fff2b3 100%);
  --message-bg-other: rgba(255, 255, 255, 0.8);
  --message-border: rgba(255, 179, 217, 0.3);
  
  /* UI Elements */
  --border-color: rgba(255, 179, 217, 0.2);
  --shadow-color: rgba(255, 179, 217, 0.15);
  --hover-color: rgba(255, 179, 217, 0.1);
}
```

#### Background Cloud Pattern
```css
/* Cute floating clouds */
.kawaii-theme {
  position: relative;
  overflow: hidden;
}

.kawaii-theme::before {
  content: '';
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-image: 
    radial-gradient(ellipse 60px 30px at 100px 50px, rgba(255, 255, 255, 0.6) 0%, transparent 50%),
    radial-gradient(ellipse 80px 40px at 300px 120px, rgba(255, 255, 255, 0.4) 0%, transparent 50%),
    radial-gradient(ellipse 50px 25px at 500px 80px, rgba(255, 255, 255, 0.5) 0%, transparent 50%),
    radial-gradient(ellipse 70px 35px at 200px 200px, rgba(255, 255, 255, 0.3) 0%, transparent 50%);
  animation: floatingClouds 20s ease-in-out infinite;
  pointer-events: none;
  z-index: -1;
}

@keyframes floatingClouds {
  0%, 100% { transform: translateX(0px) translateY(0px); }
  25% { transform: translateX(10px) translateY(-5px); }
  50% { transform: translateX(-5px) translateY(10px); }
  75% { transform: translateX(15px) translateY(5px); }
}
```

#### Header Cloud Decoration
```css
.header.kawaii {
  background: linear-gradient(135deg, #ffb3d9 0%, #fff2b3 100%);
  position: relative;
  border-radius: 0 0 20px 20px;
}

.header.kawaii::after {
  content: '☁️ ☁️ ☁️';
  position: absolute;
  top: 10px;
  right: 20px;
  font-size: 1.2rem;
  opacity: 0.6;
  animation: gentleBob 3s ease-in-out infinite;
}

@keyframes gentleBob {
  0%, 100% { transform: translateY(0px); }
  50% { transform: translateY(-3px); }
}
```

#### Rounded Message Bubbles
```css
.kawaii-theme .message-content {
  border-radius: 25px;
  padding: 15px 20px;
  background: var(--message-bg-other);
  border: 2px solid var(--border-color);
  box-shadow: 0 4px 15px var(--shadow-color);
  position: relative;
}

.kawaii-theme .own-message .message-content {
  background: var(--message-bg-own);
  border: 2px solid var(--accent-pink);
}

/* Kawaii bubble tails */
.kawaii-theme .message-content::before {
  content: '';
  position: absolute;
  width: 0;
  height: 0;
  border-style: solid;
}

.kawaii-theme .own-message .message-content::before {
  bottom: -8px;
  right: 20px;
  border-width: 8px 8px 0 8px;
  border-color: var(--accent-pink) transparent transparent transparent;
}

.kawaii-theme .message:not(.own-message) .message-content::before {
  bottom: -8px;
  left: 20px;
  border-width: 8px 8px 0 8px;
  border-color: var(--border-color) transparent transparent transparent;
}
```

#### Kawaii Buttons
```css
.kawaii-theme button {
  background: linear-gradient(135deg, var(--accent-pink) 0%, var(--accent-yellow) 100%);
  border: none;
  border-radius: 20px;
  padding: 10px 20px;
  color: var(--text-primary);
  font-weight: 500;
  box-shadow: 0 4px 10px rgba(255, 179, 217, 0.3);
  transition: all 0.3s ease;
  cursor: pointer;
}

.kawaii-theme button:hover {
  transform: translateY(-2px);
  box-shadow: 0 6px 15px rgba(255, 179, 217, 0.4);
  background: linear-gradient(135deg, var(--accent-yellow) 0%, var(--accent-pink) 100%);
}

.kawaii-theme button:active {
  transform: translateY(0px);
  box-shadow: 0 2px 5px rgba(255, 179, 217, 0.3);
}
```

#### Kawaii Input Fields
```css
.kawaii-theme input {
  background: rgba(255, 255, 255, 0.8);
  border: 2px solid var(--accent-pink);
  border-radius: 25px;
  padding: 12px 20px;
  color: var(--text-primary);
  font-size: 16px;
  box-shadow: inset 0 2px 5px rgba(255, 179, 217, 0.1);
  transition: all 0.3s ease;
}

.kawaii-theme input:focus {
  outline: none;
  border-color: var(--accent-yellow);
  box-shadow: 
    inset 0 2px 5px rgba(255, 179, 217, 0.1),
    0 0 0 3px rgba(255, 242, 179, 0.3);
  background: rgba(255, 255, 255, 0.95);
}

.kawaii-theme input::placeholder {
  color: var(--text-muted);
  font-style: italic;
}
```

#### Gentle Pulse Animation
```css
@keyframes kawaiiPulse {
  0%, 100% {
    transform: scale(1);
    box-shadow: 0 4px 15px rgba(255, 179, 217, 0.3);
  }
  50% {
    transform: scale(1.02);
    box-shadow: 0 6px 20px rgba(255, 179, 217, 0.4);
  }
}

.kawaii-theme .message-content {
  animation: kawaiiPulse 4s ease-in-out infinite;
}
```

#### Sparkle Effects
```css
.kawaii-theme .sparkle {
  position: relative;
}

.kawaii-theme .sparkle::after {
  content: '✨';
  position: absolute;
  top: -10px;
  right: -10px;
  font-size: 0.8rem;
  animation: sparkleRotate 2s linear infinite;
  opacity: 0.7;
}

@keyframes sparkleRotate {
  0% { transform: rotate(0deg) scale(1); }
  50% { transform: rotate(180deg) scale(1.2); }
  100% { transform: rotate(360deg) scale(1); }
}
```

#### Floating Hearts
```css
.kawaii-theme .floating-hearts {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  pointer-events: none;
  z-index: -1;
}

.kawaii-theme .floating-hearts::before {
  content: '💖 💕 💜 💛';
  position: absolute;
  top: 20%;
  left: 10%;
  font-size: 1.5rem;
  opacity: 0.1;
  animation: floatingHearts 15s ease-in-out infinite;
}

@keyframes floatingHearts {
  0%, 100% { transform: translateY(0px) rotate(0deg); }
  25% { transform: translateY(-20px) rotate(5deg); }
  50% { transform: translateY(10px) rotate(-3deg); }
  75% { transform: translateY(-10px) rotate(2deg); }
}
```

#### Kawaii Font Styling
```css
.kawaii-theme {
  font-family: 'Comic Sans MS', 'Chalkboard SE', 'Comic Neue', cursive, sans-serif;
}

.kawaii-theme h1 {
  color: var(--text-primary);
  text-shadow: 2px 2px 4px rgba(255, 179, 217, 0.3);
  font-weight: 600;
}

.kawaii-theme .message-username {
  color: var(--accent-pink);
  font-weight: 600;
  text-shadow: 1px 1px 2px rgba(255, 179, 217, 0.2);
}
```

#### Emoji Enhancement
```css
.kawaii-theme .message-content {
  /* Make emojis slightly larger and more prominent */
}

.kawaii-theme .message-content img.emoji {
  transform: scale(1.1);
  filter: saturate(1.2) brightness(1.1);
}
```

#### Kawaii Loading States
```css
.kawaii-theme .loading {
  color: var(--accent-pink);
}

.kawaii-theme .loading::after {
  content: ' 🌸';
  animation: kawaiiSpin 1s linear infinite;
}

@keyframes kawaiiSpin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}
```

#### Theme Toggle Addition
```jsx
// Add to ThemeToggle.jsx
const themes = [
  { name: 'Lumi', emoji: '🌟' },
  { name: 'Dark', emoji: '🌙' },
  { name: 'Galaxy', emoji: '🌌' },
  { name: 'Ocean', emoji: '🌊' },
  { name: 'Kawaii', emoji: '🌸' } // New kawaii theme
];
```

#### CSS Theme Application
```css
[data-theme="kawaii"] {
  /* Apply all kawaii styles */
}
```

#### Responsive Kawaii Design
```css
@media (max-width: 768px) {
  .kawaii-theme .message-content {
    border-radius: 20px;
    padding: 12px 16px;
  }
  
  .kawaii-theme .header::after {
    font-size: 1rem;
    right: 15px;
  }
  
  /* Reduce cloud animations on mobile for performance */
  .kawaii-theme::before {
    animation-duration: 30s;
  }
}
```

#### Kawaii Accessibility Features
```css
/* Ensure sufficient contrast */
.kawaii-theme {
  --text-contrast-ratio: 4.5; /* WCAG AA compliant */
}

/* Respect reduced motion preferences */
@media (prefers-reduced-motion: reduce) {
  .kawaii-theme * {
    animation-duration: 0.01ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 0.01ms !important;
  }
}

/* High contrast mode support */
@media (prefers-contrast: high) {
  .kawaii-theme {
    --text-primary: #4a0e2f;
    --border-color: #ff69b4;
  }
}
```

### Priority
**🌸 MEDIUM-HIGH** - Highly requested by @bowo for kawaii aesthetic

### Acceptance Criteria
- [ ] Kawaii pastel theme with pink and yellow colors
- [ ] Cute cloud decorations in background
- [ ] Rounded, bubbly UI elements
- [ ] Gentle animations and effects
- [ ] Mobile-responsive design
- [ ] Accessibility compliant
- [ ] @bowo loves the kawaii cuteness! uwu

### Labels
`enhancement`, `theme`, `kawaii`, `pastel`, `cute`, `user-requested`, `design`

---

**This will create the most adorable, kawaii chat experience with soft pastels, cute clouds, and gentle animations that @bowo will absolutely love!** 🌸💖

**Perfect for:** Kawaii enthusiasts, soft aesthetic lovers, and anyone who wants their chat to be as cute as possible! uwu ✨
