### ISSUE TITLE
💬 Reply to Specific Messages Feature

### ISSUE THREAD

**Issue by CalebBarnes** [CalebBarnes/netlify-db-chat-app#33]
## 💬 Reply to Specific Messages Feature

**Requested by**: @bowo, @brendo (live chat)

### User Feedback
- **@brendo**: "Lumi, its hard to read these long chat responses with so many mentions... maybe you should think about another way to format your texts.. even with just paragraph breaks to break up the meaning of what you are saying"
- **@bowo**: "i think brendo's suggestion is good, like entering space for the next thing you are responding about, or maybe even a "reply" to specific message feature so we can see which message you are responding to"

### Description
Implement a reply feature that allows users to reply to specific messages, making conversations clearer and easier to follow. This will help organize discussions and reduce confusion in busy chat environments.

#### Current Issues
- **Long responses with multiple mentions** are hard to read
- **Unclear context** - difficult to know which message someone is responding to
- **Conversation threading** is lost in busy chat
- **Message organization** becomes chaotic with multiple topics

#### User Experience Impact
- **Confusion** about which message is being addressed
- **Lost context** in fast-moving conversations
- **Difficulty following** multi-topic discussions
- **Poor readability** of long responses with many mentions

#### Reply Feature Design
```
┌─────────────────────────────────────────┐
│ Original Message:                       │
│ ┌─────────────────────────────────────┐ │
│ │ @bowo: "can we add search function?" │ │
│ └─────────────────────────────────────┘ │
│                                         │
│ ↳ Reply from @Lumi:                     │
│   "Great idea! Search would be perfect  │
│    for finding old messages! 🔍"        │
└─────────────────────────────────────────┘
```

#### Visual Reply Indicators
- **Reply thread line** connecting original message to reply
- **Indented replies** to show hierarchy
- **Original message preview** in reply bubble
- **"Replying to @username"** indicator
- **Click to jump** to original message

#### Database Schema
```sql
-- Add reply functionality to messages table
ALTER TABLE messages ADD COLUMN reply_to_id INTEGER REFERENCES messages(id);
ALTER TABLE messages ADD COLUMN reply_to_username VARCHAR(50);
ALTER TABLE messages ADD COLUMN reply_preview TEXT; -- First 100 chars of original

-- Index for efficient reply queries
CREATE INDEX idx_messages_reply_to ON messages(reply_to_id);
```

#### API Endpoints
```javascript
// Get message with reply context
GET /api/messages/:id/with-replies

// Send reply to specific message
POST /api/messages/:id/reply
{
  "username": "Lumi",
  "message": "Great idea! 🌟",
  "reply_to_id": 123,
  "reply_to_username": "bowo"
}

// Get reply thread
GET /api/messages/:id/thread
```

#### Frontend Components
```jsx
// Reply Button Component
const ReplyButton = ({ message, onReply }) => {
  return (
    <button 
      className="reply-btn"
      onClick={() => onReply(message)}
      title={`Reply to ${message.username}`}
    >
      ↩️ Reply
    </button>
  );
};

// Reply Preview Component
const ReplyPreview = ({ originalMessage, onCancel }) => {
  return (
    <div className="reply-preview">
      <div className="reply-header">
        <span>Replying to @{originalMessage.username}</span>
        <button onClick={onCancel}>✕</button>
      </div>
      <div className="reply-content">
        {originalMessage.message.substring(0, 100)}...
      </div>
    </div>
  );
};

// Reply Thread Component
const ReplyThread = ({ message, replies }) => {
  return (
    <div className="reply-thread">
      <div className="original-message">
        <Message message={message} />
      </div>
      {replies.map(reply => (
        <div key={reply.id} className="reply-message">
          <div className="reply-line"></div>
          <Message message={reply} isReply={true} />
        </div>
      ))}
    </div>
  );
};
```

#### Reply Button Placement
- **Hover to reveal** reply button on each message
- **Mobile**: Long press to show reply option
- **Keyboard shortcut**: `R` to reply to selected message
- **Context menu**: Right-click for reply option

#### Reply Input Interface
```
┌─────────────────────────────────────────┐
│ Replying to @bowo:                      │
│ "can we add search function?"           │
│ ─────────────────────────────────────── │
│ [Type your reply...]              [Send]│
└─────────────────────────────────────────┘
```

#### Reply Display Styles
```css
/* Reply thread styling */
.reply-thread {
  margin-left: 20px;
  border-left: 3px solid var(--accent-color);
  padding-left: 15px;
}

.reply-message {
  position: relative;
  margin-top: 8px;
}

.reply-line {
  position: absolute;
  left: -18px;
  top: 0;
  width: 15px;
  height: 2px;
  background: var(--accent-color);
}

/* Reply preview in input */
.reply-preview {
  background: var(--bg-secondary);
  border: 1px solid var(--border-color);
  border-radius: 8px;
  padding: 10px;
  margin-bottom: 10px;
  font-size: 0.9em;
  color: var(--text-secondary);
}

/* Original message reference */
.reply-reference {
  background: rgba(var(--accent-color-rgb), 0.1);
  border-left: 3px solid var(--accent-color);
  padding: 8px 12px;
  margin-bottom: 8px;
  border-radius: 0 8px 8px 0;
  font-size: 0.9em;
  cursor: pointer;
}

.reply-reference:hover {
  background: rgba(var(--accent-color-rgb), 0.15);
}
```

#### Thread Navigation
- **Jump to original** message when clicking reply reference
- **Thread view** showing all replies to a message
- **Collapse/expand** reply threads
- **Reply count** indicator on original messages

#### Smart Reply Detection
```javascript
// Auto-detect when user is replying
const detectImplicitReply = (message, recentMessages) => {
  // Check for @mentions
  const mentions = extractMentions(message);
  
  // Check for contextual keywords
  const contextKeywords = ['yes', 'no', 'that', 'it', 'this'];
  
  // Suggest reply target based on context
  if (mentions.length === 1) {
    const targetUser = mentions[0];
    const recentMessage = findRecentMessageFrom(targetUser, recentMessages);
    return recentMessage;
  }
  
  return null;
};
```

#### Reply Notifications
- **Push notifications** when someone replies to your message
- **Visual indicators** for new replies
- **Reply count badges** on original messages
- **Sound notifications** for direct replies

#### Touch Interactions
- **Long press** message to reply
- **Swipe right** to quick reply
- **Pull down** on reply to see original message
- **Tap reply reference** to jump to original

#### Mobile Reply Interface
```
┌─────────────────────────────────────────┐
│ ↩️ Replying to @bowo                    │
│ "can we add search function?"           │
│ ─────────────────────────────────────── │
│                                         │
│ [Type your reply here...]               │
│                                         │
│ [Cancel]                         [Send] │
└─────────────────────────────────────────┘
```

#### Screen Reader Support
- **ARIA labels** for reply relationships
- **Semantic HTML** for thread structure
- **Keyboard navigation** through reply threads
- **Focus management** when jumping between messages

#### Keyboard Shortcuts
- `R` - Reply to selected message
- `Escape` - Cancel reply
- `Ctrl+Enter` - Send reply
- `Tab` - Navigate through reply thread

#### Mention System
- **Auto-mention** original message author in reply
- **Smart mention suggestions** based on reply context
- **Mention notifications** work with replies

#### Search Integration
- **Search within reply threads**
- **Filter by replied messages**
- **Find all replies to a message**

#### Theme Compatibility
- **Reply styling** adapts to all themes
- **Thread lines** match theme accent colors
- **Consistent visual hierarchy** across themes

#### Efficient Loading
- **Lazy load** reply threads
- **Pagination** for long reply chains
- **Caching** of reply relationships
- **Optimized queries** for thread retrieval

#### Real-time Updates
- **Live reply notifications**
- **Real-time thread updates**
- **Efficient WebSocket events** for replies

### Priority
**💬 HIGH** - Critical for improving conversation organization and readability

### Acceptance Criteria
- [ ] Users can reply to specific messages
- [ ] Reply threads are visually clear and organized
- [ ] Original message context is preserved in replies
- [ ] Mobile reply interface works smoothly
- [ ] Keyboard shortcuts and accessibility features work
- [ ] @bowo and @brendo can follow conversations easily!
- [ ] Long responses are broken into clear, contextual replies

### Labels
`enhancement`, `reply-system`, `conversation-threading`, `user-requested`, `high-priority`, `ux-improvement`

---

**This will transform how conversations flow in the chat, making them much clearer and easier to follow!** 💬✨

**Perfect for:** Organizing discussions, reducing confusion, improving readability, and creating better conversation threading! 🧵💖
