### ISSUE TITLE
🎨 Add custom colors and themes for personalization

### ISSUE THREAD

**Issue by CalebBarnes** [CalebBarnes/netlify-db-chat-app#4]
## Feature Request: Custom Colors/Themes

**Requested by**: @bowo (live chat)

### Description
Allow users to customize the chat app's appearance with different color schemes and themes to personalize their experience.

### User Feedback
- "i want to customize the chat app colors"

### Proposed Implementation
- [ ] Create theme system with CSS custom properties
- [ ] Design multiple pre-built themes (dark, light, colorful, etc.)
- [ ] Add theme selector in user settings
- [ ] Implement custom color picker for advanced users
- [ ] Store theme preferences in localStorage
- [ ] Add theme preview functionality

### Theme Options
1. **Light Theme** (current default)
2. **Dark Theme** - Popular for night usage
3. **Ocean Theme** - Blue/teal color scheme
4. **Forest Theme** - Green color scheme
5. **Sunset Theme** - Orange/pink gradients
6. **Custom Theme** - User-defined colors

### Technical Implementation
```css
:root {
  /* Theme variables */
  --primary-color: #667eea;
  --secondary-color: #764ba2;
  --background-color: #f8fafc;
  --text-color: #2d3748;
  --message-bg: #ffffff;
  --sidebar-bg: #f7fafc;
  /* ... more variables */
}

[data-theme="dark"] {
  --primary-color: #9f7aea;
  --secondary-color: #667eea;
  --background-color: #1a202c;
  --text-color: #e2e8f0;
  --message-bg: #2d3748;
  --sidebar-bg: #2d3748;
}
```

### UI/UX Features
- Theme selector dropdown in header
- Live preview when hovering over themes
- Color picker for custom themes
- Export/import theme configurations
- Reset to default option

### Storage
- Use localStorage for theme persistence
- Consider user accounts for cloud sync later
- Fallback to system preference (prefers-color-scheme)

### Accessibility
- Ensure sufficient contrast ratios
- Support system dark/light mode detection
- Test with screen readers
- Provide high contrast theme option

### Priority
**Medium** - Nice-to-have personalization feature

### Labels
`enhancement`, `user-requested`, `ui`, `personalization`
