### ISSUE TITLE
✨ Implement Discord-style auto-mention toggle for replies

### ISSUE THREAD

**Issue by CalebBarnes** [CalebBarnes/netlify-db-chat-app#75]
## 🎯 Goal

Implement Discord-style auto-mention functionality for replies with user toggle control, ensuring better notification flow and UX consistency.

## 💡 User Feedback

**Identified Issue**: @Lumi missed a reply message because it didn't include an @mention, even though it was a direct reply.

**Discord UX Reference**: When replying to someone in Discord:
- Auto-mentions the original author by default
- Shows "@ ON" toggle button with clear visual feedback
- User can click to toggle "@ OFF" to disable pinging
- Tooltip: "Click to disable pinging the original author"
- X button positioned on far right to cancel reply

## ✅ Current State

**What Works:**
- ✅ Reply UI shows "Replying to [username]"
- ✅ Visual reply reference in sent messages
- ✅ Click reply reference to scroll to original message
- ✅ X button to cancel reply

**What's Missing:**
- ❌ Auto-mention functionality when replying
- ❌ Toggle control for mention on/off
- ❌ Clear visual feedback for mention state

### Reply Container Layout
```
[Replying to Username]           [@ ON] [X]
```

### Toggle States
- **@ ON** (default): Blue/highlighted, auto-adds @username to message
- **@ OFF**: Darker/muted, no auto-mention
- **Hover tooltip**: "Click to disable pinging the original author"

### Positioning
- **@ toggle**: Center-right of reply container
- **X button**: Far right edge (current position)

#### 1. Reply State Management
```javascript
const [replyState, setReplyState] = useState({
  isReplying: false,
  replyToId: null,
  replyToUsername: null,
  mentionEnabled: true // Default to ON
});
```

#### 2. Auto-mention Logic
```javascript
// When reply is initiated
function startReply(messageId, username) {
  setReplyState({
    isReplying: true,
    replyToId: messageId,
    replyToUsername: username,
    mentionEnabled: true // Always start with mention ON
  });
  
  // Auto-add @username to message input if mention enabled
  if (mentionEnabled) {
    setMessage(`@${username} `);
  }
}

// When mention toggle is clicked
function toggleMention() {
  const newMentionState = !replyState.mentionEnabled;
  setReplyState(prev => ({ ...prev, mentionEnabled: newMentionState }));
  
  // Update message input
  if (newMentionState) {
    // Add @username if not already present
    if (!message.includes(`@${replyState.replyToUsername}`)) {
      setMessage(`@${replyState.replyToUsername} ${message}`);
    }
  } else {
    // Remove @username from message
    setMessage(message.replace(`@${replyState.replyToUsername} `, ''));
  }
}
```

#### 3. UI Components
```jsx
{replyState.isReplying && (
  <div className="reply-container">
    <span>Replying to {replyState.replyToUsername}</span>
    <div className="reply-controls">
      <button 
        className={`mention-toggle ${replyState.mentionEnabled ? 'on' : 'off'}`}
        onClick={toggleMention}
        title={replyState.mentionEnabled ? 
          "Click to disable pinging the original author" : 
          "Click to enable pinging the original author"}
      >
        @ {replyState.mentionEnabled ? 'ON' : 'OFF'}
      </button>
      <button className="cancel-reply" onClick={cancelReply}>
        ×
      </button>
    </div>
  </div>
)}
```

#### 4. CSS Styling
```css
.reply-container {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 8px 12px;
  background: var(--reply-bg);
  border-radius: 4px;
  margin-bottom: 8px;
}

.reply-controls {
  display: flex;
  gap: 8px;
  align-items: center;
}

.mention-toggle {
  padding: 4px 8px;
  border-radius: 4px;
  border: none;
  font-size: 12px;
  font-weight: 600;
  cursor: pointer;
  transition: all 0.2s;
}

.mention-toggle.on {
  background: var(--accent-color);
  color: white;
}

.mention-toggle.off {
  background: var(--muted-bg);
  color: var(--muted-text);
}

.cancel-reply {
  background: none;
  border: none;
  font-size: 16px;
  cursor: pointer;
  color: var(--muted-text);
  padding: 4px;
}
```

### User Experience
- ✅ **Consistent notifications**: Users get pinged when someone replies to them
- ✅ **User control**: Can disable pinging if desired
- ✅ **Clear feedback**: Visual indication of mention state
- ✅ **Familiar UX**: Matches Discord's proven pattern

### AI Assistant Benefits
- ✅ **Reliable notifications**: @Lumi will be mentioned in replies by default
- ✅ **Better workflow**: Won't miss important replies during development
- ✅ **Consistent interaction**: Predictable mention behavior

### Development Benefits
- ✅ **Improved communication**: Better notification flow for all users
- ✅ **Reduced missed messages**: Auto-mention ensures visibility
- ✅ **Professional UX**: Matches industry standards

## 📋 Acceptance Criteria

- [ ] When user clicks reply, mention toggle defaults to "@ ON"
- [ ] "@ ON" state auto-adds @username to message input
- [ ] User can click toggle to switch between "@ ON" and "@ OFF"
- [ ] Toggle shows clear visual feedback (highlighted vs muted)
- [ ] Tooltip shows "Click to disable pinging the original author"
- [ ] X button remains positioned on far right
- [ ] Message input updates when toggle state changes
- [ ] Sent messages include @mention when toggle was ON
- [ ] Works with existing reply UI and functionality
- [ ] Responsive design works on mobile devices

## 🔗 Related Issues

- Related to existing reply system implementation
- Builds on mention autocomplete functionality
- Enhances notification and presence features

## 🏷️ Labels

`enhancement`, `ui-ux`, `replies`, `mentions`, `discord-style`, `notifications`, `high-priority`

---

**This feature will significantly improve the chat UX by ensuring users (including AI assistants) receive proper notifications when someone replies to their messages, while maintaining user control over the mention behavior.** 🚀✨
